version: 1.0.{build}
clone_folder: c:\gopath\src\github.com\bmeyers22\go-playground
environment:
  GOPATH: c:\gopath
cache:
  - c:\gopath\pkg\dep
install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
# Overriding config based on environment
for:

# override for production
-
  branches:
    only:
      - master

  environment:
    TEST_VAR: master
# override for staging
-
  branches:
    except:
      - master

  environment:
    TEST_VAR: not-master

build_script:
  - appveyor AddCompilationMessage "Starting Compile"
  - pwd
  - dir
  - ps: go build -ldflags="-X github.com/bmeyers22/go-playground/plugin.TestVar=gotest" ./plugin
  - ps: go build -ldflags="-X github.com/bmeyers22/go-playground/plugin.TestVar=gotest" .
  - dir
  - appveyor AddCompilationMessage "Compile Success"
  - go-playground.exe
  - plugin

deploy: off
