version: 1.0.{build}
clone_folder: c:\gopath\src\github.com\bmeyers22\go-playground
environment:
  GOPATH: c:\gopath
  RUNNER_BUCKET: staging-runner-onecloud-io
  matrix:
    - GOVERSION: 1.9.1
cache:
  - c:\gopath\pkg\dep
install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
# Overriding config based on environment
for:

# override for production
-
  branches:
    only:
      - master

  environment:
    TEST_VAR: master
# override for staging
-
  branches:
    except:
      - master

  environment:
    TEST_VAR: not-master

build_script:
  - echo "-X github.com/bmeyers22/go-playground/plugin.testVar=%TEST_VAR%" > temp.txt
  - set /p BUILD_LDFLAGS=<temp.txt
  - cat temp.txt
  - echo "%BUILD_LDFLAGS%"
  - go build -ldflags="%BUILD_LDFLAGS%" -o dist\program.exe .
artifacts:
  - path: dist\program.exe
    name: package

